version: '3'
services:
  app:
    container_name: simpleobjectstorage
    restart: unless-stopped
      # args:
    # JAR_FILE: SimpleObjectStorage-1.0-SNAPSHOT.jar
    build: .
    ports:
    - '8080:8080'

    depends_on:
    - mongo

    environment:
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_NAME: bucketDB
      DATABASE_USER: jarhan
      DATABASE_PASSWORD: 123456
      AUTHENTICATION_DATABASE: admin

    volumes:
    - './data:/app/data'
  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: jarhan
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: bucketDB
    volumes:
    - './data/db:/data/db'
    - './data/configdb:/data/configdb'